# Generated by Django 5.2.1 on 2025-05-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0002_contactrequest"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactrequest",
            options={
                "verbose_name": "Контактная заявка",
                "verbose_name_plural": "Контактные заявки",
            },
        ),
        migrations.AlterField(
            model_name="contactrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
