# Generated by Django 5.2.1 on 2025-05-21 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0003_alter_contactrequest_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactrequest",
            options={},
        ),
        migrations.RemoveField(
            model_name="contactrequest",
            name="created_at",
        ),
    ]
