# Generated by Django 5.2.1 on 2025-05-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0008_flowershop_aboutsection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flowershop",
            name="main_image",
            field=models.ImageField(blank=True, null=True, upload_to="shop_images/"),
        ),
    ]
