# Generated by Django 5.2.1 on 2025-05-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myApp", "0009_alter_flowershop_main_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=50, verbose_name="Телефон")),
                ("address", models.TextField(verbose_name="Адрес")),
                (
                    "working_hours",
                    models.CharField(max_length=100, verbose_name="Режим работы"),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="shop_images/", verbose_name="Изображение магазина"
                    ),
                ),
            ],
        ),
    ]
